### ISSUE TITLE
feat: Simulate enter key after auto submitting the 2fa in browser

### ISSUE THREAD

**Issue by viewors** [twofas/2fas-browser-extension#112]
### Feature description

So when it submits the 2fa token in the browser, it inputs the key, however i have to press enter to log in. It would be nice if the enter key was simulated automatically

### Motivation

More easy and convenient way to sign in.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Thank you, @viewors, for your report. This feature exists in browser extension, but it is turned off in default, because it's an experimental function.

1. Click right mouse button on extension icon and choose `Options`
![image](https://github.com/user-attachments/assets/bf184e3e-85f2-4990-9e36-34cb59c00402)

2. Click on `Enable auto submit for 2FA forms`
![image](https://github.com/user-attachments/assets/9dd89b22-eabc-4e05-baf2-11824189413b)

And that's it ;)
