### ISSUE TITLE
can use 2FAS without smartphone?

### ISSUE THREAD

**Issue by thangckt** [twofas/2fas-browser-extension#22]
Dear Developers,

I wonder if it is possible to use 2FAS extension only without a smartphone.

Thank you so much

**Comment by GrzegorzZajac000** [comment]
No @thangckt, you cannot use 2FA browser extension without a smartphone. This method is by design and is the safest and most secure method of authentication. The security of your secret keys is always a top priority, that's why they are not be stored in the browser's database. Each time you request a token, it is securely transmitted from your phone (where your keys are securely stored) using end-to-end encryption. This ensures that your data remain protected and the integrity of the two-factor authentication process is maintained.

**Comment by JVimes** [comment]
I second this feature request. Please let me pick my level of security. Thank you!
