### ISSUE TITLE
feat: Automticly (For some sites?) submit after typing in the token.

### ISSUE THREAD

**Issue by air2** [twofas/2fas-browser-extension#86]
### Feature description

For some sites it would save time, when the extension submits the form after filling the token. Not for all sites, just the few I choose.
So I should be able to configure this per site. (In the phone or in the extension does not matter much to me, but I guess in the phone it would work for every browser connected to my phone, so I guess that should have the preference)

### Motivation

After confirming the request on my phone, I just want to continue, so it would save some time if I do not have to hit the submit button every time.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by GrzegorzZajac000** [comment]
Thank you, @air2, for your suggestion. We've got this feature implemented some time ago, but for now it is marked as experimental and disabled by default, because it doesn't work properly for all forms. You can enable it in extension options ;)
![image](https://github.com/twofas/2fas-browser-extension/assets/12233796/2c89be7a-303d-416a-8e17-43e31775957c)
